version: '3.9'
services:
    wordpress:
        image: wordpress:latest
        ports: 
            - "8080:80"
        volumes:
            - ./wp-themes:/var/www/html/wp-content/themes
        environment:
            - WORDPRESS_DB_HOST=mysql:3306
            - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
            - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
            - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
            - WORDPRESS_DEBUG=${WORDPRESS_DEBUG}
        depends_on:
            - mysql


    mysql:
        image: mysql:8.0
        ports:
            - "5000:3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
